# Custom Language File for Launcher Customizer

[ejs.app]
title = "Atom Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/s-i-m-o-n-git/AtomLauncher/tree/main"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7YGPaek55H"

[ejs.settings]
sourceGithubLink = "https://github.com/s-i-m-o-n-git/AtomLauncher/tree/main"
supportLink = "https://github.com/s-i-m-o-n-git/AtomLauncher/tree/main"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Atom Launcher"
welcomeDescription = ""
welcomeDescCTA = ""
